name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Format Code
      run: cargo fmt --all -- --check --color=always

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - uses: actions-rs/clippy-check@v1.0.7
      with:
        name: Clippy Lint
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Hadolint Check
      uses: jbergstroem/hadolint-gh-action@v1

  test:
      name: Test
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test

  coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1.3
        with:
          args: '--ignore-tests'
  
  scan:
    needs: test
    name: Scan Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/mansong/rust-api:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'