name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
  format:
    name: Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Format Code
      run: cargo fmt --all -- --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Linter
      run: cargo clippy -- -D warnings
  
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
