name: Create Tag
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

jobs:
  tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create and Push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: mansong1
        WITH_V: true
  setfailure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Set workflow to Failure
    runs-on: ubuntu-latest
    steps:
    - name: Set Failure status
      run: exit 1